<a href="https://colab.research.google.com/github/anvarxonmajidov/Aviakompaniya_qoniqishi_praktikum/blob/anvarxonmajidov%2Fdesktop-tutorial/Aviakompaniya_qoniqishi_mohirdev.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Aviakompaniya yo'lovchilarining qoniqishi

In [ ]:
import pandas as pd
import numpy as np
import sklearn # scikit-learn kutubxonasi
from sklearn.model_selection import train_test_split
from sklearn.pipeline import Pipeline
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import OneHotEncoder, StandardScaler
from sklearn.compose import ColumnTransformer
from sklearn.linear_model import LinearRegression
from sklearn.tree import DecisionTreeRegressor
from sklearn.ensemble import RandomForestRegressor
from sklearn.model_selection import cross_val_score
from sklearn.metrics import mean_squared_error

In [ ]:
sample_sub = pd.read_csv('sample_submission.csv')
test_data = pd.read_csv('test_dataset.csv',index_col=0)
train_data = pd.read_csv('train_dataset.csv',index_col=0)
sample_sub.head()

id  satisfaction
0   1             0
1   2             0
2   3             1
3   4             1
4   5             0

In [ ]:
train_data.head()

Gender      Customer Type  Age   Type of Travel     Class  \
id                                                              
1     Male  disloyal Customer   33  Business travel       Eco   
2   Female     Loyal Customer   49  Business travel  Business   
3   Female     Loyal Customer   43  Business travel       Eco   
4   Female     Loyal Customer   27  Business travel  Business   
5     Male     Loyal Customer   11  Personal Travel       Eco   

    Flight Distance  Inflight wifi service  Departure/Arrival time convenient  \
id                                                                              
1               571                      2                                  3   
2              1431                      4                                  1   
3               867                      1                                  4   
4              1550                      3                                  3   
5               526                      3                                  4   

    Ease of Online booking  Gate location  ...  Inflight entertainment  \
id                                         ...                           
1                        2              4  ...                       4   
2                        4              4  ...                       5   
3                        4              4  ...                       1   
4                        3              3  ...                       2   
5                        3              2  ...                       4   

    On-board service  Leg room service  Baggage handling  Checkin service  \
id                                                                          
1                  3                 1                 3                4   
2                  5                 5                 5                3   
3                  1                 1                 1                1   
4                  4                 4                 5                5   
5                  5                 2                 5                3   

    Inflight service  Cleanliness  Departure Delay in Minutes  \
id                                                              
1                  3            4                          10   
2                  5            3                           0   
3                  1            2                           0   
4                  4            2                           0   
5                  5            4                           0   

    Arrival Delay in Minutes  satisfaction  
id                                          
1                        3.0             0  
2                        0.0             1  
3                       18.0             0  
4                        0.0             1  
5                       10.0             0  

[5 rows x 23 columns]

In [ ]:
train_data.isnull().sum()

Gender                                0
Customer Type                         0
Age                                   0
Type of Travel                        0
Class                                 0
Flight Distance                       0
Inflight wifi service                 0
Departure/Arrival time convenient     0
Ease of Online booking                0
Gate location                         0
Food and drink                        0
Online boarding                       0
Seat comfort                          0
Inflight entertainment                0
On-board service                      0
Leg room service                      0
Baggage handling                      0
Checkin service                       0
Inflight service                      0
Cleanliness                           0
Departure Delay in Minutes            0
Arrival Delay in Minutes             28
satisfaction                          0
dtype: int64

In [ ]:
a = train_data.describe()

In [ ]:
a.corrwith(a['satisfaction'])

Age                                  0.999980
Flight Distance                      0.892386
Inflight wifi service                1.000000
Departure/Arrival time convenient    1.000000
Ease of Online booking               1.000000
Gate location                        1.000000
Food and drink                       1.000000
Online boarding                      1.000000
Seat comfort                         1.000000
Inflight entertainment               1.000000
On-board service                     1.000000
Leg room service                     1.000000
Baggage handling                     1.000000
Checkin service                      1.000000
Inflight service                     1.000000
Cleanliness                          1.000000
Departure Delay in Minutes           0.995852
Arrival Delay in Minutes             0.995801
satisfaction                         1.000000
dtype: float64

In [ ]:
median = train_data['Arrival Delay in Minutes'].median()
train_data['Arrival Delay in Minutes'].fillna(median,inplace=True)

In [ ]:
median = test_data['Arrival Delay in Minutes'].median()
test_data['Arrival Delay in Minutes'].fillna(median,inplace=True)

In [ ]:
test_data.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 4000 entries, 1 to 4000
Data columns (total 22 columns):
 #   Column                             Non-Null Count  Dtype  
---  ------                             --------------  -----  
 0   Gender                             4000 non-null   object 
 1   Customer Type                      4000 non-null   object 
 2   Age                                4000 non-null   int64  
 3   Type of Travel                     4000 non-null   object 
 4   Class                              4000 non-null   object 
 5   Flight Distance                    4000 non-null   int64  
 6   Inflight wifi service              4000 non-null   int64  
 7   Departure/Arrival time convenient  4000 non-null   int64  
 8   Ease of Online booking             4000 non-null   int64  
 9   Gate location                      4000 non-null   int64  
 10  Food and drink                     4000 non-null   int64  
 11  Online boarding                    4000 non-null   int64

In [ ]:
train_data.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 10000 entries, 1 to 10000
Data columns (total 23 columns):
 #   Column                             Non-Null Count  Dtype  
---  ------                             --------------  -----  
 0   Gender                             10000 non-null  object 
 1   Customer Type                      10000 non-null  object 
 2   Age                                10000 non-null  int64  
 3   Type of Travel                     10000 non-null  object 
 4   Class                              10000 non-null  object 
 5   Flight Distance                    10000 non-null  int64  
 6   Inflight wifi service              10000 non-null  int64  
 7   Departure/Arrival time convenient  10000 non-null  int64  
 8   Ease of Online booking             10000 non-null  int64  
 9   Gate location                      10000 non-null  int64  
 10  Food and drink                     10000 non-null  int64  
 11  Online boarding                    10000 non-null  int

In [ ]:
train_set, test_set = train_test_split(train_data, test_size=0.2, random_state=42)

In [ ]:
X_train = train_set.drop("satisfaction", axis=1)
y = train_set["satisfaction"].copy()

X_num = X_train.drop(["Gender","Customer Type","Type of Travel","Class"],axis=1)

In [ ]:
Y_num = test_set.drop(["Gender","Customer Type","Type of Travel","Class"],axis=1)

In [ ]:
y.head()

id
9255    1
1562    1
1671    0
6088    1
6670    1
Name: satisfaction, dtype: int64

In [ ]:
X_num.head()

Age  Flight Distance  Inflight wifi service  \
id                                                  
9255   23             1368                      4   
1562   56              493                      5   
1671   18              109                      3   
6088   41              733                      2   
6670   57             1843                      4   

      Departure/Arrival time convenient  Ease of Online booking  \
id                                                                
9255                                  1                       4   
1562                                  1                       1   
1671                                  1                       3   
6088                                  2                       2   
6670                                  4                       4   

      Gate location  Food and drink  Online boarding  Seat comfort  \
id                                                                   
9255              4               4                4             4   
1562              1               3                2             5   
1671              3               2                3             2   
6088              2               5                5             5   
6670              4               5                4             4   

      Inflight entertainment  On-board service  Leg room service  \
id                                                                 
9255                       4                 5                 1   
1562                       5                 5                 5   
1671                       2                 1                 4   
6088                       2                 2                 2   
6670                       3                 3                 3   

      Baggage handling  Checkin service  Inflight service  Cleanliness  \
id                                                                       
9255                 2                2                 3            4   
1562                 5                2                 5            2   
1671                 2                2                 3            2   
6088                 2                4                 2            5   
6670                 3                4                 3            3   

      Departure Delay in Minutes  Arrival Delay in Minutes  
id                                                          
9255                           0                       0.0  
1562                           0                       0.0  
1671                          71                      83.0  
6088                           0                       3.0  
6670                           0                       0.0

#Sonli ustunlar uchun

In [ ]:
num_pipeline = Pipeline([
          ('imputer', SimpleImputer(strategy='median')),
          ('std_scaler', StandardScaler())             
])

#Matnli ustunlar uchun

In [ ]:
num_attribs = list(X_num)
cat_attribs = ["Gender","Customer Type","Type of Travel","Class"]

full_pipeline = ColumnTransformer([
    ('num', num_pipeline, num_attribs),
    ('cat', OneHotEncoder(), cat_attribs)
])

In [ ]:
num_attribs

['Age',
 'Flight Distance',
 'Inflight wifi service',
 'Departure/Arrival time convenient',
 'Ease of Online booking',
 'Gate location',
 'Food and drink',
 'Online boarding',
 'Seat comfort',
 'Inflight entertainment',
 'On-board service',
 'Leg room service',
 'Baggage handling',
 'Checkin service',
 'Inflight service',
 'Cleanliness',
 'Departure Delay in Minutes',
 'Arrival Delay in Minutes']

In [ ]:
cat_attribs

['Gender', 'Customer Type', 'Type of Travel', 'Class']

In [ ]:
X_prepared = num_pipeline.fit_transform(X_num)
X_prepared[0:5,:]

array([[-1.10707276,  0.13840187,  0.89635433, -1.35285433,  0.84527775,
         0.79829065,  0.58908527,  0.47803934,  0.3836404 ,  0.44630608,
         1.21412626, -1.83079898, -1.4026589 , -1.07382214, -0.57098283,
         0.52547051, -0.3707791 , -0.37544819],
       [ 1.11031485, -0.72012183,  1.6300186 , -1.35285433, -1.26198993,
        -1.54045149, -0.16397995, -1.00310501,  1.15015469,  1.19940639,
         1.21412626,  1.21308149,  1.11407357, -1.07382214,  1.12553068,
        -1.00679269, -0.3707791 , -0.37544819],
       [-1.44304058, -1.09689108,  0.16269005, -1.35285433,  0.14285519,
         0.01870994, -0.91704518, -0.26253284, -1.14938817, -1.05989456,
        -1.90777333,  0.45211137, -1.4026589 , -1.07382214, -0.57098283,
        -1.00679269,  1.47641705,  1.77161451],
       [ 0.10241139, -0.48464104, -0.57097422, -0.6968852 , -0.55956737,
        -0.76087078,  1.3421505 ,  1.21861151,  1.15015469, -1.05989456,
        -1.12729843, -1.06982886, -1.4026589 ,  0.507

In [ ]:
LR_model = LinearRegression()
DT_model  = DecisionTreeRegressor()
RF_model = RandomForestRegressor()

#LinearRegression

In [ ]:
LR_model.fit(X_prepared, y)

LinearRegression()

In [ ]:
test_set1 = Y_num.drop("satisfaction",axis=1)

In [ ]:
y1 = Y_num["satisfaction"].copy()

In [ ]:
test_data_prepared = num_pipeline.transform(test_set1)
test_data_prepared

array([[-0.70391138,  0.37290148,  0.16269005, ...,  1.29160211,
        -0.3707791 , -0.37544819],
       [-0.0991693 ,  2.33916604,  0.89635433, ...,  0.52547051,
         0.22760839,  0.29712567],
       [-0.50233068, -0.87907136,  0.89635433, ...,  0.52547051,
        -0.3707791 , -0.37544819],
       ...,
       [ 0.16960495, -0.35807012,  0.16269005, ..., -0.24066109,
        -0.16264432, -0.37544819],
       [-0.63671781,  0.43863987,  1.6300186 , ..., -1.77292429,
         2.75124255,  2.39245192],
       [ 0.6399599 , -0.93892272,  0.16269005, ...,  0.52547051,
        -0.3187454 , -0.37544819]])

In [ ]:
predicted_data = LR_model.predict(test_data_prepared)
predicted_data[:5]

array([0.76517315, 1.05313558, 0.73268186, 0.08427542, 0.4020708 ])

In [ ]:
ls_predicte = []
for i in predicted_data:
  if i>0.5:
    ls_predicte.append(1)
  else:
    ls_predicte.append(0)

In [ ]:
pd.DataFrame({'Prognoz':ls_predicte, 'Real baxosi': y1}).head()

Prognoz  Real baxosi
id                        
6253        1            0
4685        1            1
1732        1            1
4743        0            0
4522        0            0

In [ ]:
lin_mse = mean_squared_error(y1, ls_predicte)
# RMSE hisoblaymiz
lin_rmse = np.sqrt(lin_mse)
print(lin_rmse)

0.4129164564412516


In [ ]:
X_test_prepared = full_pipeline.transform(test_data)
X_test_prepared

array([[-0.97268563,  1.44924491, -0.57097422, ...,  0.        ,
         1.        ,  0.        ],
       [ 0.6399599 ,  0.3886002 , -1.3046385 , ...,  1.        ,
         0.        ,  0.        ],
       [ 0.77434703, -0.87220317,  0.89635433, ...,  1.        ,
         0.        ,  0.        ],
       ...,
       [-0.0991693 , -0.6131743 , -0.57097422, ...,  0.        ,
         1.        ,  0.        ],
       [-1.10707276, -0.24425441,  1.6300186 , ...,  0.        ,
         1.        ,  0.        ],
       [-0.97268563, -0.13828805,  0.16269005, ...,  0.        ,
         1.        ,  0.        ]])

In [ ]:
LR_predicted = LR_model.predict(X_test_prepared)
LR_predicted[:10]

array([0.16425657, 0.5951016 , 1.09709968, 0.35334548, 0.49594065,
       0.36316439, 0.30909436, 0.92174515, 0.05058621, 0.12250205])

In [ ]:
ls_y_predicte = []
for i in LR_predicted:
  if i>0.4:
    ls_y_predicte.append(1)
  else:
    ls_y_predicte.append(0)
ls_y_predicte[:10]

[0, 1, 1, 0, 1, 0, 0, 1, 0, 0]

#DecisionTreeRegressor

In [ ]:
DT_model.fit(X_prepared, y)

DecisionTreeRegressor()

In [ ]:
predicted_data1 = DT_model.predict(test_data_prepared)
predicted_data1[:5]

array([0., 1., 1., 0., 0.])

In [ ]:
ls_dt_predicte = []
for i in predicted_data1:
  if i>0.5:
    ls_dt_predicte.append(1)
  else:
    ls_dt_predicte.append(0)
ls_dt_predicte[:10]

[0, 1, 1, 0, 1, 1, 1, 1, 1, 0]

In [ ]:
pd.DataFrame({'Prognoz':ls_dt_predicte, 'Real baxosi': y1})

Prognoz  Real baxosi
id                        
6253        0            0
4685        1            1
1732        1            1
4743        0            0
4522        1            0
...       ...          ...
6413        1            1
8286        0            0
7854        0            0
1096        1            1
6930        1            1

[2000 rows x 2 columns]

In [ ]:
lin_mse = mean_squared_error(y1, ls_dt_predicte)
# RMSE hisoblaymiz
lin_rmse = np.sqrt(lin_mse)
print(lin_rmse)

0.26267851073127396


In [ ]:
DT_predicted = DT_model.predict(X_test_prepared)
DT_predicted[:10]

array([0., 0., 1., 1., 0., 0., 0., 1., 0., 0.])

#RandomForestRegressor

In [ ]:
RF_model.fit(X_prepared, y)

RandomForestRegressor()

In [ ]:
predicted_data2 = RF_model.predict(test_data_prepared)
predicted_data2[:5]

array([0.  , 1.  , 1.  , 0.  , 0.51])

In [ ]:
ls_rf_predicte = []
for i in predicted_data2:
  if i>0.5:
    ls_rf_predicte.append(1)
  else:
    ls_rf_predicte.append(0)
ls_rf_predicte[:10]

[0, 1, 1, 0, 1, 1, 1, 0, 1, 0]

In [ ]:
pd.DataFrame({'Prognoz':ls_rf_predicte, 'Real baxosi': y1})

Prognoz  Real baxosi
id                        
6253        0            0
4685        1            1
1732        1            1
4743        0            0
4522        1            0
...       ...          ...
6413        1            1
8286        0            0
7854        0            0
1096        1            1
6930        1            1

[2000 rows x 2 columns]

In [ ]:
lin_mse = mean_squared_error(y1, ls_rf_predicte)
# RMSE hisoblaymiz
lin_rmse = np.sqrt(lin_mse)
print(lin_rmse)

0.23021728866442676


In [ ]:
RF_predicted = RF_model.predict(X_test_prepared)
RF_predicted[:10]

array([0.  , 0.28, 1.  , 1.  , 0.34, 0.  , 0.05, 1.  , 0.  , 0.01])

In [ ]:
ls_f_predicte = []
for i in RF_predicted:
  if i>0.5:
    ls_f_predicte.append(1)
  else:
    ls_f_predicte.append(0)
ls_f_predicte[:10]

[0, 0, 1, 1, 0, 0, 0, 1, 0, 0]

In [ ]:
sample_sub['satisfaction'] = ls_f_predicte
sample_sub

id  satisfaction
0        1             0
1        2             0
2        3             1
3        4             1
4        5             0
...    ...           ...
3995  3996             1
3996  3997             0
3997  3998             0
3998  3999             1
3999  4000             0

[4000 rows x 2 columns]

In [ ]:
sample_sub.to_csv("sample_sub_submission.csv", index=False)
sample_sub

id  satisfaction
0        1             0
1        2             0
2        3             1
3        4             1
4        5             0
...    ...           ...
3995  3996             1
3996  3997             0
3997  3998             0
3998  3999             1
3999  4000             0

[4000 rows x 2 columns]

In [ ]:
pd.read_csv('sample_submission.csv')

id  satisfaction
0        1             0
1        2             0
2        3             1
3        4             1
4        5             0
...    ...           ...
3995  3996             1
3996  3997             0
3997  3998             0
3998  3999             1
3999  4000             0

[4000 rows x 2 columns]